
--- VER REGISTROS DESDE AYER
	SELECT  * 
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	WHERE FECHA > GETDATE()-1
	ORDER BY fecha DESC


--- VER FACTURAS DE NEGOCIACION 108
	SELECT  U_CAJERO, ESTADO, U_PAIS, U_TIENDA, U_SERIE, U_NUMERO, TOTAL, NIT_REAL, U_NOM, U_FECHA,  TELEFONO_ENTREGA, COMMENTS, U_NEGOCIACION , U_DIRECCION,   UUID_FEL, ERROR, ESFEL
	FROM VENTAS.TRI_FACTURAS 
	WHERE U_NEGOCIACION = 33
	--AND U_NUMERO IN (118541)
	ORDER BY U_FECHA DESC



--- PARA INSERTAR EN CENTRAL
	 BEGIN TRAN A

	 --IF OBJECT_ID('tempdb..##VERIFICAR_FACTURAS_CURSOR') IS NOT NULL  
	 --BEGIN  
	 --  DROP TABLE ##VERIFICAR_FACTURAS_OOSIGU_T
	 --END


	 INSERT INTO [VENTAS].[TBL_FACTURA_OSIGU] 
	SELECT  A.U_TIENDA, A.U_SERIE, A.U_NUMERO, 
	SUBSTRING(COMMENTS, PATINDEX('%AUTORIZACION:%', COMMENTS)+14 , PATINDEX('%, RECLAMO:%', COMMENTS)-PATINDEX('%AUTORIZACION:%', COMMENTS)-14) AS AUTORIZACION, 
	SUBSTRING(COMMENTS, PATINDEX('%RECLAMO:%', COMMENTS)+9 , PATINDEX('% ]%', COMMENTS)-PATINDEX('%RECLAMO:%', COMMENTS)-9) AS RECLAMO, 
	A.U_CAJERO AS USUARIO_FCV, A.U_FECHA AS FECHA, A.TOTAL AS TOTAL_SEGURO,
	486.73 AS TOTAL_CLIENTE, 0 AS ESTADO, '' AS FECHA_EMVIO, '' AS DESCRIPCION
	FROM VENTAS.TRI_FACTURAS A
	INNER JOIN VENTAS.TBL_FACTURAS_DET_PAGOS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO - 1 = B.U_NUMERO 
	WHERE U_NEGOCIACION = 108
	AND U_NIT LIKE '%U_NIT%'
	AND A.U_NUMERO NOT IN (SELECT A.U_NUMERO
						FROM [VENTAS].[TBL_FACTURA_OSIGU] A
						INNER JOIN VENTAS.TRI_FACTURAS B
						ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
						AND U_NEGOCIACION IN  (108))
	--AND A.U_NUMERO  IN (55527)


					
	SELECT * FROM  ##VERIFICAR_FACTURAS_OOSIGU_T
	ORDER BY FECHA ASC


	ROLLBACK TRAN A
	COMMIT TRAN A

	DROP TABLE ##VERIFICAR_FACTURAS_OOSIGU_T




--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION 
	SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	--AND U_NEGOCIACION IN  ( 108)
	--AND A.ESTADO = 0
	--AND A.U_NUMERO = 2949072465
	AND A.U_SERIE = '09139BFC'
	--AND FECHA > GETDATE()-1
	--AND A.U_TIENDA IN (640)
	ORDER BY FECHA asc


	--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION 
	SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, B.COMMENTS, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	AND U_NEGOCIACION IN  ( 33)
	AND A.ESTADO = 0
	--AND A.U_NUMERO = 49317
	--AND FECHA > GETDATE()-1
	--AND A.U_TIENDA IN (640)
	ORDER BY FECHA DESC




--- PARA ACTUALIZAR FECHA_EMVIO
	 UPDATE  [VENTAS].[TBL_FACTURA_OSIGU]
	 SET FECHA_ENVIO = GETDATE()
	 WHERE U_NUMERO IN (SELECT A.U_NUMERO
						FROM [VENTAS].[TBL_FACTURA_OSIGU] A
						INNER JOIN VENTAS.TRI_FACTURAS B
						ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
						AND U_NEGOCIACION IN  (108))


--- PARA INSERTAR REGISTROS A TIENDAS DESDE CENTRAL
    SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, A.*,

    'INSERT INTO ['+C.DIRECCIONIP+'].['+C.db_genesis+'].[VENTAS].[TBL_FACTURA_OSIGU]
    SELECT
    A.U_SERIE, A.U_NUMERO, A.AUTORIZACION, A.RECLAMO, A.USUARIO_FCV, A.FECHA, A.TOTAL_SEGURO, A.TOTAL_CLIENTE, A.ESTADO, A.FECHA_ENVIO, A.DESCRIPCION
    FROM [VENTAS].[TBL_FACTURA_OSIGU] A
    INNER JOIN VENTAS.TRI_FACTURAS B
    ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
    AND U_NEGOCIACION IN  (108)
    AND A.ESTADO = 0
    AND A.U_NUMERO = '+ CONVERT(NVARCHAR(20),A.U_NUMERO) +'
    AND A.U_SERIE = '''+A.U_SERIE+'''' AS INSERT_DESDE_CENTRAL,
	'SELECT *  
	FROM  ['+C.DIRECCIONIP+'].['+C.db_genesis+'].[VENTAS].[TBL_FACTURA_OSIGU]       
	WHERE ESTADO = 0  AND FECHA_ENVIO > GETDATE()-1  ' AS VER_INSERT

    FROM [VENTAS].[TBL_FACTURA_OSIGU] A
    INNER JOIN VENTAS.TRI_FACTURAS B
    ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
    INNER JOIN PRODUCCION.TBL_TIENDAS C
    ON A.U_TIENDA = C.U_TIENDA
    AND U_NEGOCIACION IN  (108)
    AND A.ESTADO = 0
    ORDER BY U_TIENDA ASC
