

--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION
-- DEL 01 AL 15 DE SEPTIEMRE NEG 33
	SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	AND A.AUTORIZACION IN ('PR-8JK5XW3J',
'PR-GDL35GQJ',
'PR-7DGM3LXD',
'PR-8JK56E7J',
'PR-EDE824RJ',
'PR-7DVPQNPD',
'PR-GDL35WQJ',
'PR-VDRQR2KJ',
'PR-GDL356EJ',
'PR-WJYR988D',
'PR-8JK56ZPJ',
'PR-ZD55E3VD',
'PR-PJ26R2GJ',
'PR-VDRQL7YJ',
'PR-WJYR2G9D',
'PR-PDX2V5KD',
'PR-PDX2VPKD',
'PR-PDX2V6XD',
'PR-3J368W5D',
'PR-XJ7G6EPJ',
'PR-MJQQWYQJ',
'PR-VDRQLN8J',
'PR-PJ26RP4J',
'PR-WJYR2X6D',
'PR-7DVPYXMD',
'PR-PJ26R94J',
'PR-EDE82R5J',
'PR-PJ26RYZJ',
'PR-VDRQLRNJ',
'PR-7DGM8WND',
'PR-7DVPYQND',
'PR-PJ26RWZJ',
'PR-MJQQWW2J',
'PR-8JPG3M7D',
'PR-KJZ89WVJ',
'PR-WJYR6GPD',
'PR-9D9GQYZD',
'PR-2J8G7R3D',
'PR-XJ7GR2WJ',
'PR-VDRQXQWJ',
'PR-MJQQ4KZJ',
'PR-8JPG35ED',
'PR-9D9GQL8D',
'PR-PDX2ELPD',
'PR-MJQQ42NJ',
'PR-MJQQ4YXJ',
'PR-GDL3REGJ',
'PR-NJ66VYKJ',
'PR-XJ7GR6KJ',
'PR-VDWV86PJ',
'PR-NJ66VV2J',
'PR-KJZPVVKJ',
'PR-GDL2PPQD',
'PR-9D9GQQLD',
'PR-2J8GXXPD',
'PR-8JPG47WD',
'PR-KJZ8R5MJ',
'PR-KJZ8336J',
'PR-7DGM33LD',
'PR-RJN43MLJ',
'PR-KJZ8RLRJ',
'PR-EDE8MMKJ',
'PR-PJ26R5XJ',
'PR-8JK56K7J',
'PR-VDRQL3YJ',
'PR-6JM49GKD',
'PR-LD463P3D',
'PR-NJ6644EJ',
'PR-PJ26MMRJ',
'PR-PDX2V3ND',
'PR-NJ66Q25J',
'PR-MJQQ243J',
'PR-6JM4ZWND',
'PR-XJ7G672J',
'PR-NJ66QMQJ',
'PR-NJ66VZXJ',
'PR-PJ26WR3J',
'PR-6JM47KPD',
'PR-8JPG3PZD',
'PR-NJ66V8KJ',
'PR-6JM47EGD',
'PR-WJYR65PD',
'PR-7DGMWK8D',
'PR-VDRQLVNJ',
'PR-3J3659PD',
'PR-RJN4QYXJ',
'PR-7DGN22XJ',
'PR-RJN4Q6PJ',
'PR-WJYR9NWD',
'PR-VDRQLQ6J',
'PR-VDRQL48J',
'PR-8JPG465D',
'PR-8JPGV92D',
'PR-GDL3MG5J',
'PR-KJZ83R6J',
'PR-ZD55E9VD',
'PR-8JPG484D',
'PR-6JM49LZD',
'PR-VDWV665J',
'PR-GDL355EJ',
'PR-7DVPY9ZD',
'PR-VDWVPR4J',
'PR-MJQQWLQJ',
'PR-3J368VWD',
'PR-ZD55NE8D',
'PR-ZD55EK9D',
'PR-KJZ8R6RJ',
'PR-ZD55EW9D',
'PR-PDX2VGGD',
'PR-PDX2VYGD',
'PR-NJ66QNMJ',
'PR-GDL3MW5J',
'PR-3J36996D',
'PR-7DVPQVQD',
'PR-MJQQWGLJ',
'PR-PDX2VLXD',
'PR-6JM479QD',
'PR-KJZ89QWJ',
'PR-PDX2E6PD',
'PR-EDE893NJ',
'PR-PDX2EKRD',
'PR-EDE89QNJ',
'PR-PDX2ERPD',
'PR-VDRQXXKJ',
'PR-RJN4QKNJ',
'PR-WJYR26ED',
'PR-PDX2E9RD',
'PR-PDX2VE3D',
'PR-7DGMWRZD',
'PR-ZD55YG6D',
'PR-8JPGVX2D',
'PR-7DVPQ7QD',
'PR-7DGM876D',
'PR-8JK56GQJ',
'PR-EDE827WJ',
'PR-LD4675GD',
'PR-PJ26MK3J',
'PR-NJ66QP5J',
'PR-2J8GMERD',
'PR-3J36E9KD',
'PR-6JM493KD',
'PR-XJ7G64VJ',
'PR-RJN43G3J',
'PR-VDWVPZMJ',
'PR-PJ26MPRJ',
'PR-VDWV6NPJ',
'PR-EDE82LRJ',
'PR-3J36959D',
'PR-7DVPYK2D',
'PR-GDL3M95J',
'PR-7DVPY8MD',
'PR-XJ7G682J',
'PR-GDL359QJ',
'PR-PJ26RXVJ',
'PR-2J8GX3PD',
'PR-6JM47PLD',
'PR-KJZ892WJ',
'PR-GDL3RZ8J',
'PR-8JPG3WPD',
'PR-3J365QKD',
'PR-8JPG3KED',
'PR-3J365GKD',
'PR-PJ26WX2J',
'PR-WJYR6MXD',
'PR-PDX2E22D',
'PR-6JM47KGD',
'PR-RJN4QQXJ',
'PR-7DGMW58D',
'PR-WJYR28ED',
'PR-EDE82VEJ',
'PR-2J8G7Y5D',
'PR-WJYR6NGD',
'PR-PDX2E4MD',
'PR-7DVP2NKD',
'PR-NJ66VRKJ',
'PR-NJ66VM2J',
'PR-6JM47ZQD',
'PR-7DVP2KXD',
'PR-KJZ89RKJ',
'PR-7DVP2ZKD')
	ORDER BY FECHA asc



	
--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION
-- DEL 01 AL 15 DE SEPTIEMRE NEG 108
	SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	AND A.AUTORIZACION IN ('PR-XJ7GRWKJ',
'PR-8JPG3V2D',
'PR-9D9GQ28D',
'PR-ZD5MQQQD',
'PR-VDRQX4QJ',
'PR-WJYR6NXD',
'PR-3J3658PD',
'PR-WJYR6EGD',
'PR-2J8G7VMD',
'PR-LD46G33D',
'PR-LD46G73D',
'PR-VDWV8QWJ',
'PR-RJN4QLNJ',
'PR-LD46G4VD',
'PR-RJN4QXXJ',
'PR-XJ7GR9KJ',
'PR-MJQQ4WNJ')
	ORDER BY FECHA asc
--
-- Las facturas de la negociacion 108 empiezan a partir de 12 de septiembre




--
--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION
-- DEL 16 AL 30 DE SEPTIEMRE NEG 33
	SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	AND A.AUTORIZACION IN ('PR-PJ23GGRD',
'PR-3J3MQ76J',
'PR-9D9Y4P3D',
'PR-EDEN3KKJ',
'PR-RJN8VG8J',
'PR-WJYY77WJ',
'PR-PDXZ9K7D',
'PR-WJYY778J',
'PR-7DVW3MQJ',
'PR-LD4M5E4J',
'PR-WJYY7P8J',
'PR-8JPWLRYD',
'PR-VDRG37XJ',
'PR-WJYY7G8J',
'PR-PJ23G8XD',
'PR-PJ23G3XD',
'PR-8JPWLMYD',
'PR-NJ659L8D',
'PR-VDRG38XJ',
'PR-KJZPV5EJ',
'PR-ZD5MQM4D',
'PR-8JPWL2WD',
'PR-6JMRVNND',
'PR-EDEN3NWJ',
'PR-XJ7MYKZJ',
'PR-PDXZ94ND',
'PR-MJQG7G3J',
'PR-LD4M5RWJ',
'PR-VDRG3KYJ',
'PR-7DVW3Z2J',
'PR-8JPWLQ4D',
'PR-VDRG3N4J',
'PR-8JPWL95D',
'PR-MJQG7VLJ',
'PR-NJ659RMD',
'PR-WJYY7MVJ',
'PR-9D9Y429D',
'PR-2J8ZP88J',
'PR-6JMRVMZD',
'PR-RJN8VWLJ',
'PR-NJ659P3D',
'PR-8JKLYM9D',
'PR-LD4M5QLJ',
'PR-KJZPV9RJ',
'PR-7DVWM3MJ',
'PR-2J8ZPMRJ',
'PR-PJ23QG4D',
'PR-VDRG638J',
'PR-8JKLYVQD',
'PR-GDL2PR5D',
'PR-WJYY766J',
'PR-RJN8VXVJ',
'PR-KJZPV3RJ',
'PR-8JPWLY5D',
'PR-8JPWL4LD',
'PR-RJN8G55J',
'PR-MJQGXXQJ',
'PR-9D9YVZ4D',
'PR-2J8Z99EJ',
'PR-EDEN735J',
'PR-VDWW9ZKD',
'PR-WJYY726J',
'PR-6JMRPP7D',
'PR-8JKL3YQD',
'PR-8JPWRLLD',
'PR-VDRG67NJ',
'PR-8JKL3Z5D',
'PR-MJQGX82J',
'PR-7DVWM9NJ',
'PR-GDL2VYKD',
'PR-WJYYP5EJ',
'PR-RJN8GR5J',
'PR-WJYYPWEJ',
'PR-8JPWRG7D',
'PR-6JMRPYLD',
'PR-2J8Z9Z5J',
'PR-EDEN7NNJ',
'PR-NJ65ZKQD',
'PR-VDRG6G9J',
'PR-WJYYPGEJ',
'PR-GDL2VQKD',
'PR-WJYYPYPJ',
'PR-7DGN5E8J',
'PR-PDXZG2RD',
'PR-VDRG69NJ',
'PR-GDL2VZRD',
'PR-3J3M4Y7J',
'PR-XJ7M4NGJ',
'PR-2J8Z9K5J',
'PR-NJ65ZXXD',
'PR-LD4MLZYJ',
'PR-3J3M4MKJ',
'PR-2J8Z9W3J',
'PR-6JMRP5PD',
'PR-7DVWM5GJ',
'PR-7DGN548J',
'PR-MJQGX54J',
'PR-7DVWM5XJ',
'PR-3J3M4V3J',
'PR-VDRG6VQJ',
'PR-EDEN7MZJ',
'PR-6JMRPMGD',
'PR-8JKL3QVD',
'PR-6JMRPQPD',
'PR-PDXZGQMD',
'PR-PDXZGEPD',
'PR-WJYY55WJ',
'PR-LD4ML76J',
'PR-ZD5MGYXD',
'PR-PDXZGVPD',
'PR-2J8Z9MMJ',
'PR-EDEN793J',
'PR-2J8Z97MJ',
'PR-MJQG88XJ',
'PR-PJ23QR7D')
	ORDER BY FECHA asc

-- 

-- Las facturas de la Negociacion 33 Terminan el 26 de septiembre 


	--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION
-- DEL 16 AL 30 DE SEPTIEMRE NEG 108
		SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	AND A.AUTORIZACION IN ('PR-VDRG66NJ',
'PR-WJYY749J',
'PR-2J8ZPZQJ',
'PR-8JPWRRLD',
'PR-7DVW3KZJ',
'PR-EDEN3RRJ',
'PR-VDRG33XJ',
'PR-MJQG7LLJ',
'PR-3J3MQP5J',
'PR-PDXZGY3D',
'PR-RJN8VM3J',
'PR-PJ23GZGD',
'PR-NJ659GED',
'PR-8JPWLP5D',
'PR-2J8ZP84J',
'PR-RJN8VQ7J',
'PR-XJ7MY8PJ',
'PR-XJ7M4Q8J',
'PR-NJ659W3D',
'PR-KJZPVV6J',
'PR-2J8ZP6QJ',
'PR-KJZPVXPJ',
'PR-VDRG3V4J',
'PR-3J3MQ46J',
'PR-3J3MQXNJ',
'PR-PDXZ9XKD',
'PR-7DGN2NQJ',
'PR-VDRG3GYJ',
'PR-MJQG7K3J',
'PR-XJ7MQ2KJ',
'PR-VDRG78KJ',
'PR-7DVW9XZJ',
'PR-VDRG79KJ',
'PR-ZD5M484D',
'PR-8JPW7WYD',
'PR-GDL2YQQD',
'PR-7DGNX4LJ',
'PR-MJQG89NJ',
'PR-6JMRX2QD',
'PR-RJN85K8J',
'PR-8JPW76WD',
'PR-8JKLZGPD',
'PR-VDRG6RRJ',
'PR-7DVWMYVJ',
'PR-PJ2342RD',
'PR-8JKLZE3D',
'PR-MJQG8Z3J',
'PR-GDL2VKRD',
'PR-RJN85E3J',
'PR-PDXZGN2D',
'PR-VDRG7ZKJ',
'PR-EDENKNKJ',
'PR-VDRG7QXJ',
'PR-RJN8588J',
'PR-XJ7MQN4J',
'PR-3J3MG29J',
'PR-EDENKP6J',
'PR-PJ23QP2D',
'PR-8JPW7E2D',
'PR-MJQG833J',
'PR-XJ7MQX4J',
'PR-XJ7MQ3KJ',
'PR-WJYY53WJ',
'PR-7DGNXQXJ',
'PR-LD4M944J',
'PR-7DGNXVQJ',
'PR-9D9YZY3D',
'PR-NJ65KG2D',
'PR-VDRG76RJ',
'PR-VDWWZ3PD',
'PR-PJ23QW7D',
'PR-7DGN5GPJ',
'PR-8JPW7QWD',
'PR-3J3MGN6J',
'PR-MJQG8N3J',
'PR-6JMRXQMD',
'PR-8JKLZ8GD',
'PR-XJ7MQPVJ',
'PR-PJ23QY2D',
'PR-MJQG8K9J',
'PR-EDENKZKJ',
'PR-EDENK33J',
'PR-MJQG859J',
'PR-7DVWMQVJ',
'PR-6JMRXKND',
'PR-ZD5M4L4D',
'PR-PJ234NRD',
'PR-VDRG7KXJ',
'PR-7DVW9ZQJ')
	ORDER BY FECHA asc

-- 

-- Las Facturas de la negociacion 108 sigen hasta el 30 de Septiembre



--- VER FACTURAS DE NEGOCIACION 108
	SELECT  U_CAJERO, ESTADO, U_TIENDA, U_SERIE, U_NUMERO, TOTAL, NIT_REAL, U_NOM, U_FECHA,  TELEFONO_ENTREGA, COMMENTS, U_NEGOCIACION , U_DIRECCION,   UUID_FEL, ERROR, ESFEL
	FROM VENTAS.TRI_FACTURAS 
	WHERE U_NEGOCIACION = 33
	AND CAST(U_FECHA AS DATE) > '2024-09-26'
	--AND COMMENTS LIKE '%, RECLAMO: %'
	AND NIT_REAL = '725269'
	AND U_TIENDA != 67
	ORDER BY U_FECHA DESC



		--- PARA VER REGISTROS DE OSIGU CON SU NEGOCIACION 
	SELECT B.U_NEGOCIACION,  B.U_NOM, B.U_NIT, B.COMMENTS, A.*
	FROM [VENTAS].[TBL_FACTURA_OSIGU] A
	INNER JOIN VENTAS.TRI_FACTURAS B
	ON A.U_TIENDA = B.U_TIENDA AND A.U_SERIE = B.U_SERIE AND A.U_NUMERO = B.U_NUMERO
	WHERE B.U_NEGOCIACION = 33
	AND CAST(B.U_FECHA AS DATE) > '2024-09-26'
	--AND U_FECHA > GETDATE()-19
	AND B.COMMENTS LIKE '%, RECLAMO:%'
	ORDER BY U_FECHA DESC





	--- VER FACTURAS DE NEGOCIACION 108
	SELECT  U_CAJERO, ESTADO, U_PAIS, U_TIENDA, U_SERIE, U_NUMERO, TOTAL, NIT_REAL, U_NOM, U_FECHA,  TELEFONO_ENTREGA, COMMENTS, U_NEGOCIACION , U_DIRECCION,   UUID_FEL, ERROR, ESFEL
	FROM VENTAS.TRI_FACTURAS 
	WHERE ESTADO = 1
	AND U_NUMERO IN (78000)
	AND U_SERIE = 'FESCM363A'
	--AND U_TIENDA = 672
	--AND CAST(U_FECHA AS DATE) = '2024-10-04'
	--AND U_NEGOCIACION IN (33, 108)
	ORDER BY U_FECHA DESC



	-- TABLAS DE REFERENCIAS
--   VENTAS
	DECLARE @USerie VARCHAR(10) = 'FESCM363A           '
	DECLARE @UNumero INT = 78000

	--DECLARE @UTIENDA INT = (SELECT TOP 1 U_TIENDA FROM VENTAS.TRI_FACTURAS)
	DECLARE @UTIENDA INT = 672


	SELECT  U_CAJERO, ESTADO, U_PAIS, U_TIENDA, U_SERIE, U_NUMERO, TOTAL, NIT_REAL, U_NOM, U_FECHA,  TELEFONO_ENTREGA, COMMENTS, U_NEGOCIACION , U_DIRECCION,   UUID_FEL, ERROR, ESFEL
	FROM VENTAS.TRI_FACTURAS WHERE U_SERIE = @USerie AND U_NUMERO = @UNumero AND U_TIENDA = @UTIENDA
	-----
	SELECT * FROM VENTAS.TRI_FACTURAS_XML WHERE U_SERIE = @USerie AND U_NUMERO = @UNumero  AND U_TIENDA = @UTIENDA
	-----
	SELECT A.U_PAIS, A.U_TIENDA, A.U_SERIE, A.U_NUMERO, A.ITEMCODE,  B.ITEMCODE_SUSTITUTO, B.NOMBRECORTO, A.CANT_SOLICITADA, PRICE, PRCOFERTA, PRC_ASEG, DESC_ASEG, DISCPRCNT, PRECIO_NETO, SUB_TOTAL
	FROM VENTAS.TRI_FACTURAS_DET A
	INNER JOIN PRODUCCION.TBL_PRODUCTOS B
	ON A.ITEMCODE = B.ITEMCODE WHERE A.U_SERIE = @USerie AND A.U_NUMERO = @UNumero AND A.U_TIENDA = @UTIENDA

	SELECT DP.U_TIPO_PAGO, TP.NOMBRE, DP.U_PAIS,	DP.U_TIENDA,	DP.U_TIPOMOVIMIENTO,	DP.U_CORRELATIVO,	DP.U_SERIE,	DP.U_NUMERO,	DP.CANTIDAD,DP.U_BANCO,	DP.AUTORIZACION
	FROM VENTAS.TBL_FACTURAS_DET_PAGOS DP
	INNER JOIN VENTAS.TBL_TIPOS_PAGOS TP
	ON DP.U_TIPO_PAGO = TP.U_TIPO_PAGO
	WHERE DP.U_SERIE = @USerie AND DP.U_NUMERO = @UNumero AND DP.U_TIENDA = @UTIENDA

	SELECT * FROM VENTAS.TBL_IMPRESION_FACTURAS WHERE U_SERIE = @USerie AND U_NUMERO = @UNumero AND U_TIENDA = @UTIENDA

	SELECT U_NEGOCIACION, NOMBRE, EMPRESA_NOMBRE, NIT, NO_TRANESPECIAL, CONDICIONES, QUERY 
	FROM VENTAS.TRI_NEGOCIACIONES_ESPECIALES 
	WHERE U_NEGOCIACION IN (SELECT U_NEGOCIACION FROM VENTAS.TRI_FACTURAS WHERE U_SERIE = @USerie AND U_NUMERO = @UNumero AND U_TIENDA = @UTIENDA)



